{% set name = "zarr-checksum" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zarr_checksum-{{ version }}.tar.gz
  sha256: be1038f1161603b55dc29c6322179904484bdc548685a19a2c8291d7d7bbe949

build:
  entry_points:
    - zarrsum = zarr_checksum.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7,<4.0
    - boto3 >=1.24,<2.0
    - zarr >=2.12,<3.0
    - click >=8.1.3,<9.0
    - tqdm >=4.64.1,<5.0
    - pydantic >=2.0,<3.0

test:
  imports:
    - zarr_checksum
  commands:
    - pip check
    - zarrsum --help
  requires:
    - pip

about:
  home: https://github.com/dandi/zarr_checksum
  summary: Checksum support for zarrs stored in various backends
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlmightyYakob
    - jwodder
    - yarikoptic
