{% set name = "zarr-checksum" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zarr_checksum-{{ version }}.tar.gz
  sha256: 6abb81188d4128c5960498f777ef93d5e5ff2cb12d16312cc031676988f759f3

build:
  entry_points:
    - zarrsum = zarr_checksum.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7,<4.0
    - boto3 >=1.24,<2.0
    - zarr >=2.12,<3.0
    - click >=8.1.3,<9.0
    - tqdm >=4.64.1,<5.0
    - pydantic >=1.10.2,<2.0

test:
  imports:
    - zarr_checksum
  commands:
    - pip check
    - zarrsum --help
  requires:
    - pip

about:
  home: https://github.com/dandi/zarr_checksum
  summary: Checksum support for zarrs stored in various backends
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlmightyYakob
