{% set name = "zarr-checksum" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zarr_checksum-{{ version }}.tar.gz
  sha256: 081f163d52533a286bc8249a241da5614b5dab0c06377b208980dc205e272da9

build:
  entry_points:
    - zarrsum = zarr_checksum.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - click >=8.1.3,<9.0
    - tqdm >=4.64.1,<5.0

test:
  requires:
    - boto3 >=1.24,<2.0
    - pip
    - pytest
    - zarr >=2.12,<3.0
    - python {{ python_min }}
  imports:
    - zarr_checksum
  commands:
    - pip check
    - zarrsum --help
    - python -m pytest -vv --pyargs zarr_checksum

about:
  home: https://github.com/dandi/zarr_checksum
  summary: Checksum support for zarrs stored in various backends
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jjnesbitt
    - yarikoptic
